# Basics of Numpy

In [87]:
type([[123,35,25,65,90],[],[]])     ### Baisc arrange of rows and columns in list

list

In [88]:
import numpy

In [89]:
n=numpy.arange(27)

In [90]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [91]:
n.reshape(3,3,3)   #three dimensional shape

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
type(n)

numpy.ndarray

In [93]:
import cv2    # This is used as image to array's (Numpy)

In [94]:
im_g=cv2.imread("smallgray.png",0)    ## This is the Command used to read image
print(im_g)                                  ## These are no. of rows and columns does our image has.
                                                #1 indicates 3 dimensional array #0 indicates 2 dimensional array
# Converting images to array

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


## Converting arrays to images 
cv2.iwrite("newimage.png",im_g)

#Indexing, Slicing and iterating numpy arrays

In [95]:
a=[1,2,3]

In [96]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [97]:
im_g[0:2,2:4]           ## Slicing 1st 2 rows and columns from im_g

array([[104, 121],
       [255, 255]], dtype=uint8)

In [98]:
im_g.shape                # Shape or dimensional of Numpy array in im_g

(3, 5)

In [99]:
 im_g[1,4]                          # indexing 

147

Iterating through rows

In [100]:
for i in im_g:                                  
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


Iterating through columns

In [101]:
for j in im_g.T:
    print(j)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


Iterating through line by line

In [102]:
for k in im_g.flat:
    print(k)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


# Stacking and Splitting the Numpy Arrays

In [103]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [104]:
#Stacking is nothing but Concatinating arrays horizontally
#1.Horizontal Stacking
x=numpy.hstack((im_g,im_g))
x

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [105]:
#2. Vertical Stacking  Concating arrays vertically
x=numpy.vstack((im_g,im_g))
x

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [106]:
# Splitting
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [107]:
# Horizontal Split
x=numpy.hsplit(im_g,5)
x

[array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8)]

In [108]:
#Vertical Split
y=numpy.vsplit(im_g,3)
y

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]

In [109]:
#Horizonatl Split
y=numpy.hsplit(im_g,5)

In [110]:
y

[array([[187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182]], dtype=uint8)]

In [111]:
y[0]

array([[187],
       [198],
       [209]], dtype=uint8)

In [112]:
y[0][0]

array([187], dtype=uint8)